version: "3.2"
services:
  app:
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application-dev
    command: ["make", "server"]

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "$PWD/app:/etc/caddy/app"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
        - app
    container_name: caddy

volumes:
  caddy_data:
  caddy_config:
