version: "3.2"
services:
  app:
    image: glagius/devops-for-programmers-project-lvl1:latest
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    depends_on:
      - db

  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    container_name: database

  test:
    image: glagius/devops-for-programmers-project-lvl1:latest
    command: ["make", "test"]
