version: "3.2"
services:
  app:
    image: glagius/devops-for-programmers-project-lvl1:latest
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
