version: "3.1"
services:
  app:
    image: devops-for-programmers-project-lvl1:latest
    build:
      context: .
      dockerfile: Dockerfile

  production:
    image: devops-for-programmers-project-lvl1:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["make", "test"]
    env_file:
      - .env
