FROM node:14.6

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

ARG NODOS_DB_TYPE
ARG NODOS_DB_HOSTNAME
ARG NODOS_DB_USERNAME
ARG NODOS_DB_PASSWORD

EXPOSE 8080

CMD ["npm", "start"]